# Get current finger length, finger height, fingertip offset, finger orientation
int64 index       # device type, 0 for single, 1 for dual primary, 2 for dual secondary
bool grip         # True if External grip, false if internal grip
---
#Result
float64 min_width
float64 max_width

